name: fbtl_screenshots
description: A package for taking screenshots of Flutter apps using Firebase Test Lab.
version: 0.0.1
repository: https://github.com/speaking-in-code/fbtl_screenshots

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
